@echo off
cd %~dp0
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
echo Activating virtual environment...
call venv\Scripts\activate
echo Installing/Updating dependencies...
pip install -r requirements.txt
echo Downloading spaCy model...
python -m spacy download en_core_web_sm
echo Starting FastAPI server...
uvicorn app.main:app --reload
pause
